services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Withdrawing\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/WithdrawingBundle.php'
